### ISSUE TITLE
Minor Glitch on the top of the first Let's Fight of Rygar game

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Arcade-Tecmo_MiSTer#5]
Sorry I don't have the real PCB to verify it and doesn't have an answer on the forum.
https://misterfpga.org/viewtopic.php?f=25&t=518

This video shows a glitch on the first Let's Fight -> https://imgur.com/a/P9zSvlE

Test done with the last version 20200616 and the issue remains.
Thanks,

**Comment by nullobject** [comment]
@wwark Thanks for the capture.

These little glitches are mostly likely related to DMA timing issues.

I will try to figure them out from the schematic, but I'm waiting on a real PCB (it's shipping to me now) to be able to nail these timings properly.

**Comment by wwark** [comment]
Closed corrected with the last test rbf.

**Comment by nullobject** [comment]
Great. I will make an official release with these changes shortly.
