### ISSUE TITLE
Sprite frame buffer question

### ISSUE THREAD

**Issue by gyurco** [MiSTer-devel/Arcade-Tecmo_MiSTer#6]
Hi!

It's not really an issue, but a question: is there any reason why a line buffer cannot be used for the sprite layer? I'm sure the original arcade machine didn't use a buffer for the whole frame (as non of the sprite machines used that). It consumes huge BRAM resources, makes your otherwise great core porting to other platforms hard.

**Comment by nullobject** [comment]
@gyurco I'm really sorry, I don't know how I missed this issue.

Are you sure about this?

I own a Rygar PCB and from what I can tell there is a dual frame buffer used for the sprites. It is implemented using a bunch of NTE4164 64k DRAM chips all in parallel.

If these were only used as line buffers, then why would they need so much RAM?

![rygar-sprite-buffer](https://user-images.githubusercontent.com/3614/106347848-aba34880-6315-11eb-881b-290de00bbd5a.png)

**Comment by gyurco** [comment]
That's an interesting and unusual (and probably an expensive for its time) design. But I'm still not sure if LREAD and RREAD is toggling by every line or every frame (as these select between the two banks). The clock for the flip-flop which generates them is disabled in VBL (clk = ~vbl & h_v_cont), thus it can be toggled only in the active area (by H.V.CONT, which I don't know what it is).

**Comment by gyurco** [comment]
I found the full schematics, looks like the H.V.CONT is the BLANK (composite) clocked by the SP.CONT (or SP.COUNT in the first page, where the counters are) signal.
SP.COUNT is zero when {HC,HB,HA}=5, thus in every 8th pixel. That means H.V.COUNT is basically composite BLANK synced to a certain position in the horizontal counter (when HC goes from 5 to 6).
If it's the composte BLANK, then LREAD and RREAD are toggled in every line - DRAMs (for read at least) used as a dual-line buffer.

More interesting is the address generator for these DRAMs (CR0-7 and CL0-7).
The address generator seems to feed Y and X (either from the HV counters or the sprite RAM logic), selected again by LREAD and RREAD (so the mode toggles in every line).
Prbably Y used for the RAS address, and X for the CAS address. So the DRAMs are storing the sprites for the whole frame, but really used as a dual-line buffer.
